In [1]:
#Código utilizado para generar 6 distintas energías a partir de valores aleatorios de los momentos y los ángulos. 
# Elaborado por Gustavo Ardila y Cristian Tibambre 

import numpy as np

In [2]:
# Función que calcula el Hamiltoniano dado un k
def Hamiltoniano (k):
    g=9.8
    m=5
    #Lista de energías
    E=np.zeros(6)
    # Se genera una energía para cada posición del arreglo
    for i in range(6):
        #Se generan momentos aleatorios
        pt1=np.random.uniform(low=-5, high=5)
        pt2=np.random.uniform(low=-5, high=5)
        #Ángulos aleatorios
        theta1=np.random.uniform(low=0, high=2*np.pi)
        theta2=np.random.uniform(low=0, high=2*np.pi)
        #Hamiltoniano
        H=((pt1**2)/(2*m))+((pt2**2)/(2*m))+0.5*k*(np.sin(theta1)-np.sin(theta2))**2- m*g*(np.cos(theta1)+np.cos(theta2))
        #Agrega el Hamiltoniano al arreglo y lo aproxima al entero más cercano
        E[i]= round(abs(H))
    return E

In [26]:
Hamiltoniano(0.5)

array([42., 70.,  1., 17., 18., 21.])

In [6]:
Hamiltoniano(0)

array([ 7., 35., 74., 89., 61.,  2.])

In [9]:
Hamiltoniano(5)

array([26., 22.,  8., 82., 24., 44.])

In [4]:
Hamiltoniano(20)

array([14., 31., 33.,  3., 47., 74.])

In [6]:
Hamiltoniano(10000)

array([10800.,  8179.,    23.,   133.,  3651.,    75.])

In [7]:
Hamiltoniano(1000000)

array([  99018., 1973083.,  655986., 1085112., 1093636., 1002681.])

In [11]:
Hamiltoniano(100)

array([110.,  44., 193.,   5., 113.,  41.])